### ISSUE TITLE
Docker Compose build command fails with "Maximum call stack size exceeded" error

### ISSUE THREAD

**Issue by lunadesign** [mcguinness/saml-idp#63]
I'm not sure if I'm doing something wrong but on Windows 10 and CentOS 7.8 when I perform the "docker-compose build" command, I'm getting a "Maximum call stack size exceeded" error.

Here's the full output on CentOS:

```
$ docker-compose build
Building saml-idp
Step 1/12 : FROM node:latest
 ---> 3509e57cfda1
Step 2/12 : ADD ./package.json package.json
 ---> Using cache
 ---> 813d22843647
Step 3/12 : RUN npm install --loglevel verbose
 ---> Running in 25cd0d1eb356
npm verb cli [
npm verb cli   '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '--loglevel',
npm verb cli   'verbose'
npm verb cli ]
npm info using npm@7.0.2
npm info using node@v15.0.0
npm timing config:load:defaults Completed in 2ms
npm timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
npm timing config:load:builtin Completed in 1ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 1ms
npm timing config:load:file:/.npmrc Completed in 1ms
npm timing config:load:project Completed in 1ms
npm timing config:load:file:/root/.npmrc Completed in 0ms
npm timing config:load:user Completed in 0ms
npm timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:cafile Completed in 0ms
npm timing config:load:validate Completed in 1ms
npm timing config:load:setUserAgent Completed in 0ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 9ms
npm verb npm-session b4af5ee683f22558
npm timing npm:load Completed in 23ms
npm http fetch GET 200 https://registry.npmjs.org/npm 130ms
npm http fetch GET 200 https://registry.npmjs.org/npm 12ms (from cache)
npm timing arborist:ctor Completed in 1ms
npm timing idealTree Completed in 25ms
npm timing command:install Completed in 30ms
npm notice 
npm notice New patch version of npm available! 7.0.2 -> 7.0.3
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.0.3>
npm notice Run `npm install -g npm@7.0.3` to update!
npm notice 
npm verb stack RangeError: Maximum call stack size exceeded
npm verb stack     at Node.get parent [as parent] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:691:5)
npm verb stack     at Node.get resolveParent [as resolveParent] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:949:17)
npm verb stack     at Node.resolve (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:956:32)
npm verb stack     at Node.resolve (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:958:28)
npm verb stack     at Node.resolve (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:958:28)
npm verb stack     at Node.resolve (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:958:28)
npm verb stack     at Node.resolve (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:958:28)
npm verb stack     at Node.resolve (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:958:28)
npm verb stack     at Node.resolve (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:958:28)
npm verb stack     at Node.resolve (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:958:28)
npm verb cwd /
npm verb Linux 3.10.0-1127.19.1.el7.x86_64
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--loglevel" "verbose"
npm verb node v15.0.0
npm verb npm  v7.0.2
npm ERR! Maximum call stack size exceeded
npm verb exit 1
npm timing npm Completed in 504ms
```

**Comment by yiyangli-okta** [comment]
https://github.com/npm/cli/issues/2031 it's a docker image issue. One of the comments in that issue offers a workaround. 

Simply change the based image from `node:latest` to `node:14`. Hope it helps.

**Comment by cap0** [comment]
cool it works
