### ISSUE TITLE
error on "force sign-in"

### ISSUE THREAD

**Issue by jafarmollaei** [mcguinness/saml-idp#7]
Hi.
I used "saml-idp" and "saml-sp" projects, together.
When I click on “force sign-in”   button, then an error appear (in profile page):

/home/user/saml-idp-master/views/user.hbs: (((intermediate value)(intermediate value) && stack1.forceAuthn) || helpers.helperMissing).call is not a function

TypeError: /home/user/saml-idp-master/views/user.hbs: (((intermediate value)(intermediate value) && stack1.forceAuthn) || helpers.helperMissing).call is not a function
    at eval (eval at createFunctionContext (/home/user/saml-idp-master/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:6:127)
    at Object.prog [as fn] (/home/user/saml-idp-master/node_modules/handlebars/dist/cjs/handlebars/runtime.js:219:12)
    at Object.<anonymous> (/home/user/saml-idp-master/node_modules/handlebars/dist/cjs/handlebars/helpers/if.js:19:22)
    at eval (eval at createFunctionContext (/home/user/saml-idp-master/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:14:32)
    at Object.prog [as fn] (/home/user/saml-idp-master/node_modules/handlebars/dist/cjs/handlebars/runtime.js:219:12)
    at Object.<anonymous> (/home/user/saml-idp-master/node_modules/handlebars/dist/cjs/handlebars/helpers/if.js:19:22)
    at Object.eval (eval at createFunctionContext (/home/user/saml-idp-master/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:6:32)
    at main (/home/user/saml-idp-master/node_modules/handlebars/dist/cjs/handlebars/runtime.js:173:32)
    at ret (/home/user/saml-idp-master/node_modules/handlebars/dist/cjs/handlebars/runtime.js:176:12)
    at ret (/home/user/saml-idp-master/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:525:21)

![1](https://cloud.githubusercontent.com/assets/15166281/19828206/5814f93c-9dcd-11e6-9d69-b64359d1347c.jpg)
![2](https://cloud.githubusercontent.com/assets/15166281/19828207/58186838-9dcd-11e6-9737-4ac7a63dda9c.jpg)

**Comment by mcguinness** [comment]
Just pushed an update to resolve this.  Pull latest and try again.
