### ISSUE TITLE
next is not a function

### ISSUE THREAD

**Issue by CC-Derek** [mcguinness/saml-idp#78]
I'm getting `next() is not a function` in response to a SAML auth

```
/me//git/saml-idp/node_modules/samlp/lib/samlp.js:146
        if (err) return next(err);
                        ^

TypeError: next is not a function
    at <redacted>/node_modules/samlp/lib/samlp.js:146:25
    at <redacted>/node_modules/samlp/lib/samlp.js:94:21
    at Immediate.<anonymous> (<redacted>/node_modules/saml/lib/utils.js:13:7)
    at process.processImmediate (node:internal/timers:471:21)
```

I'm on `Node.js v18.3.0` 

I'm getting 304 redirects through the auth chain, but then at the end it's throwing the error.  I see no indication in the output as to why.  I saw a previous thread from several years ago about some decompression, but there was no solution indicated in that thread.

How do I troubleshoot/fix this?

**Comment by ASCRees** [comment]
I have the same issue with node.js 16.15.1 LTS. Are there any suggestions for this?

**Comment by CC-Derek** [comment]
I solved the issue by setting a breakpoint in the internal lib and looking at the actual error there.  My issue was that my certs were malformed due to a copy/paste issue, hopefully this approach can give you more insight into your issue.
